### ISSUE TITLE
Feature Request:  Monitor.lua

### ISSUE THREAD

**Issue by ereidelbach** [asherao/DCS-Resolution-Launcher--DReLa-#1]
I absolutely love this tool and can't thank you enough for making it.  As someone who switches between DCS configs quite a bit (simpit vs desk) this tool is a life saver.

Having said, one new feature I would love to see should you everr have the time is:

1. Add support for monitor.lua files located in the Saved Games/DCS folder vice the DCS installation folder.
    - Helios users make use of the Saved Games folder by default

I've been digging through the code a bit (my first experience with C#) and found the "UserSettings.txt" import functions.  Very nice and a huge QoL upgrade!  I was going to request additional monitor resolutions until I found this functionality instead and I just made my own .txt file and it's been working great.

Thanks again!

**Comment by asherao** [comment]
Hello there. I am glad that you find the tool as useful as I do. I also have a similar gaming setup, which ultimately led to the development of DreLa. 

I took come time to give a shot at the feature request. I didn't even know that Monitor.Lua files in `Saved Games/DCS/Config/MonitorSetup` was even an option. Thank _you_! DreLa has been updated to v4 with the request implemented and can be found here: https://www.digitalcombatsimulator.com/en/files/3312032/
You should also see DReLa v4 on Git too.

**Comment by ereidelbach** [comment]
Fantastic work Bailey.  Thanks for jumping on this so quickly.  It works like a charm now!  And thanks for all that you do for the community...your work has been absolutely incredible.

I'm a Python guy by trade but you've inspired me to dabble in C# moving forward in the hopes that I might be able to give back at some point.  Glad I could be of assistance in some small way.

Happy Holidays!

-Stewie (aka Eric)

**Comment by asherao** [comment]
Thank you for the nice words. They are very much appreciated.

I look forward to seeing what you conjure up. I learned C# exclusively for a DCS project, and look where we have ended up :D

Good luck and Happy Holidays to you too!
